# Generated by Django 2.2.19 on 2023-05-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
    ]
